### ISSUE TITLE
publish npm package

### ISSUE THREAD

**Issue by travi** [travi/javascript-scaffolder#32]
- [x] ignore tag builds
```yml
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
```
- [ ] maybe ignore for pre-release tags too?
- [x] rollup config
- [x] install `rollup` as a `devDependency`
- [x] publish to `npm` using `semantic-release`
```yml
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
```
- [ ] include encrypted `GH_TOKEN` and `NPM_TOKEN`
